import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/Navbar/Navbar";
import Footer from "@/shared/Footer/Footer";
import Container from "@/shared/Container/Container";
import AppProviders from "@/provider/AppProviders";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Keen Keeper | Friends",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`} data-theme={"light"}
    >
      <body className="min-h-screen flex flex-col">
        <AppProviders>
          <Navbar />
          <main className="flex-1 bg-[#f8fafc]">
            <Container>{children}</Container>
          </main>
          <Footer />
        </AppProviders>
        <ToastContainer />
      </body>
    </html>
  );
}
